Implementation of reversing a String.
Ephyrall/reverseRepo pull request #1
Opened 2023-12-25 11:45 UTC by Ephyrall

Uploaded a new file with a solution to the task of reversing the string.

2023-12-25 18:47 UTC, saber0008 requested changes
please organize your project using standart structure
```
- src
    - main
      - java
        - <package>
```
https://jenkov.com/tutorials/maven/directory-structure.html

2023-12-25 18:47 UTC, saber0008 commented on initializereverse.java
> +public class initializereverse {
please pay closer attention to class names
https://google.github.io/styleguide/javaguide.html#s5.2.2-class-names

2023-12-25 18:47 UTC, saber0008 commented on initializereverse.java
> +//////////
please remove this unnecessary comment

2023-12-25 18:47 UTC, saber0008 commented on initializereverse.java
> +   private static boolean isNumber(char number) {
please use Character.isDigit()

2023-12-25 18:47 UTC, saber0008 commented on initializereverse.java
> +   public static void main(String[] args) {
this method has at least three responsibilities: reading user input, reversing string, priting result.
IMO its worth to decompose this code a bit.
I'd suggest you to extract the logic of reversing a string into different class.
https://www.baeldung.com/java-single-responsibility-principle

2023-12-25 18:47 UTC, saber0008 commented on initializereverse.java
> +         System.out.print(charArray[i]);
please don't print each character, just print full result once

2023-12-27 00:30 UTC, Ephyrall reviewed
Some review. Testing.

2023-12-27 13:06 UTC, saber0008 requested changes
Looks good overall but project directory structure is not entirely correct, please see comment from previous review.
Also please don't commit `.idea` folder, it is your local IDE configs.
We should only commit the source code (with some rare exceptions). All local configurations, IDE settings, etc. we should exclude using .gitignore

2023-12-29 07:56 UTC, saber0008 requested changes
Remove `.idea` folder from repository.
Also please don't forget to update directory structure.

2023-12-29 07:56 UTC, saber0008 commented on stringReverse.iml
> +<?xml version="1.0" encoding="UTF-8"?>
you need to remove this config file from repository

2023-12-29 07:56 UTC, saber0008 commented on src/Main.java
> +public class Main {
still missing

2023-12-29 07:56 UTC, saber0008 commented on src/Main.java
> +        InputHandler userInput = new InputHandler();
don't forget to update variable names after rename

2023-12-29 07:56 UTC, saber0008 commented on src/Main.java
> +        String ManipulatedString = stringManipulator.reverseStringWithoutDigits(input);
non compliant variable name

2023-12-29 07:56 UTC, saber0008 commented on src/StringManipulator.java
> +        char[] charArray = input.toCharArray();
same comment as previously
https://github.com/Ephyrall/reverseRepo/pull/1#discussion_r1437021720

2023-12-29 07:56 UTC, saber0008 commented on src/StringManipulator.java
> +        char temporaryChar;
No need to duplicate variable type in name

2023-12-29 16:00 UTC, Ephyrall commented
> Remove `.idea` folder from repository. Also please don't forget to update directory structure.

Done

2023-12-29 19:25 UTC, saber0008 requested changes

2023-12-29 19:25 UTC, saber0008 commented on src/EphyralCorp/InputHandler.java
> +package EphyralCorp;
please use only lowercase in package names 
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#:~:text=Naming%20Conventions,a%20programmer%20at%20example.com%20.

2023-12-29 19:32 UTC, saber0008 approved these changes

2023-12-30 00:13 UTC, merged